using System;
using System.Collections.Generic;
using System.IO;
using LabImager.Models.Reporting;
using PdfSharp.Drawing;
using PdfSharp.Pdf;
using PdfSharp.Fonts;

namespace LabImager.Services.Reporting
{
    public sealed class EvidencePdfExportService : IEvidencePdfExportService
    {
        private static void EnsureFontResolver()
        {
            if (GlobalFontSettings.FontResolver is null)
            {
                GlobalFontSettings.FontResolver = new WindowsFontResolver();
            }
        }

        public string Export(EvidencePdfExportRequest request)
        {
            EnsureFontResolver();

            if (string.IsNullOrWhiteSpace(request.EvidenceImagePath) ||
                !File.Exists(request.EvidenceImagePath))
            {
                throw new FileNotFoundException("Evidence image was not found.", request.EvidenceImagePath);
            }

            var outputPath = string.IsNullOrWhiteSpace(request.OutputPdfPath)
                ? Path.ChangeExtension(request.EvidenceImagePath, ".pdf")
                : request.OutputPdfPath;

            var outputDirectory = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrWhiteSpace(outputDirectory))
            {
                Directory.CreateDirectory(outputDirectory);
            }

            using var document = new PdfDocument();
            document.Info.Title = "Lab Imager Evidence Report";
            document.Info.Author = "Lab Imager";
            document.Info.Subject = request.ProjectName;

            var page = document.AddPage();
            page.Width = XUnit.FromPoint(612);
            page.Height = XUnit.FromPoint(792);

            using var gfx = XGraphics.FromPdfPage(page);

            var titleFont = new XFont("Segoe UI", 18, XFontStyleEx.Bold);
            var headingFont = new XFont("Segoe UI", 10, XFontStyleEx.Bold);
            var bodyFont = new XFont("Segoe UI", 9, XFontStyleEx.Regular);
            var smallFont = new XFont("Segoe UI", 8, XFontStyleEx.Regular);

            const double margin = 36;
            double y = margin;

            gfx.DrawString("LAB IMAGER EVIDENCE REPORT", titleFont, XBrushes.Black, new XRect(margin, y, page.Width.Point - margin * 2, 24), XStringFormats.TopLeft);
            y += 34;

            DrawMetadataLine(gfx, headingFont, bodyFont, "Project", request.ProjectName, margin, ref y);
            DrawMetadataLine(gfx, headingFont, bodyFont, "Board / Device", request.BoardOrDevice, margin, ref y);
            DrawMetadataLine(gfx, headingFont, bodyFont, "Technician", request.Technician, margin, ref y);
            DrawMetadataLine(gfx, headingFont, bodyFont, "Captured", request.CapturedAt.ToString("yyyy-MM-dd HH:mm:ss"), margin, ref y);
            DrawMetadataLine(gfx, headingFont, bodyFont, "Exported", request.ExportedAt.ToString("yyyy-MM-dd HH:mm:ss"), margin, ref y);
            DrawMetadataLine(gfx, headingFont, bodyFont, "Camera", request.SourceName, margin, ref y);
            DrawMetadataLine(gfx, headingFont, bodyFont, "Capture Format", request.CaptureFormat, margin, ref y);

            y += 14;

            using (var image = XImage.FromFile(request.EvidenceImagePath))
            {
                var maxWidth = page.Width.Point - 48;
                var maxHeight = 420.0;

                var scale = Math.Min(maxWidth / image.PixelWidth, maxHeight / image.PixelHeight);
                var imageWidth = image.PixelWidth * scale;
                var imageHeight = image.PixelHeight * scale;
                var imageX = (page.Width.Point - imageWidth) / 2.0;

                gfx.DrawRectangle(XPens.LightGray, imageX - 1, y - 1, imageWidth + 2, imageHeight + 2);
                gfx.DrawImage(image, imageX, y, imageWidth, imageHeight);

                y += imageHeight + 24;
            }

            gfx.DrawString("Notes", headingFont, XBrushes.Black, new XRect(margin, y, page.Width.Point - margin * 2, 14), XStringFormats.TopLeft);
            y += 18;

            var notes = string.IsNullOrWhiteSpace(request.NotesText)
                ? "No notes entered."
                : request.NotesText.Trim();

            foreach (var line in WrapText(notes, 92))
            {
                if (y > page.Height.Point - 54)
                {
                    page = document.AddPage();
                    page.Width = XUnit.FromPoint(612);
                    page.Height = XUnit.FromPoint(792);
                    y = margin;
                }

                using var pageGfx = gfx;
                gfx.DrawString(line, bodyFont, XBrushes.Black, new XRect(margin, y, page.Width.Point - margin * 2, 12), XStringFormats.TopLeft);
                y += 12;
            }

            gfx.DrawString("Generated by Lab Imager", smallFont, XBrushes.Gray, new XRect(margin, page.Height.Point - 32, page.Width.Point - margin * 2, 12), XStringFormats.TopLeft);

            document.Save(outputPath);
            return outputPath;
        }

        private static void DrawMetadataLine(XGraphics gfx, XFont labelFont, XFont valueFont, string label, string value, double x, ref double y)
        {
            gfx.DrawString(label + ":", labelFont, XBrushes.Black, new XRect(x, y, 110, 14), XStringFormats.TopLeft);
            gfx.DrawString(string.IsNullOrWhiteSpace(value) ? "-" : value, valueFont, XBrushes.Black, new XRect(x + 116, y, 390, 14), XStringFormats.TopLeft);
            y += 15;
        }

        private static IEnumerable<string> WrapText(string text, int maxLength)
        {
            foreach (var rawLine in text.Replace("\r\n", "\n").Split('\n'))
            {
                var words = rawLine.Split(' ', StringSplitOptions.RemoveEmptyEntries);
                var current = string.Empty;

                foreach (var word in words)
                {
                    if ((current.Length + word.Length + 1) > maxLength)
                    {
                        if (!string.IsNullOrWhiteSpace(current))
                        {
                            yield return current;
                        }

                        current = word;
                    }
                    else
                    {
                        current = string.IsNullOrWhiteSpace(current)
                            ? word
                            : current + " " + word;
                    }
                }

                if (!string.IsNullOrWhiteSpace(current))
                {
                    yield return current;
                }

                if (words.Length == 0)
                {
                    yield return string.Empty;
                }
            }
        }
    }
}


