using System;
using System.IO;
using System.Net;
using System.Text;
using LabImager.Models.Capture;

namespace LabImager.Services.Reporting;

public sealed class HtmlEvidenceReportService
    : IHtmlEvidenceReportService
{
    public string GenerateReport(
        CaptureRecord captureRecord,
        string outputDirectory)
    {
        Directory.CreateDirectory(outputDirectory);

        var reportPath = Path.Combine(
            outputDirectory,
            $"{captureRecord.CapturedAt:yyyyMMdd-HHmmss}_lab-imager-evidence-report.html");

        var evidenceImagePath = !string.IsNullOrWhiteSpace(captureRecord.AnnotatedImagePath)
            ? captureRecord.AnnotatedImagePath
            : captureRecord.OriginalImagePath;

        var imageHtml = BuildImageHtml(evidenceImagePath);
        var session = captureRecord.Session;

        var html = BuildHtml(
            captureRecord,
            imageHtml,
            session.ProjectName,
            session.BoardOrDevice,
            session.Technician,
            session.SourceName,
            session.NotesText);

        File.WriteAllText(reportPath, html, Encoding.UTF8);

        return reportPath;
    }

    private static string BuildHtml(
        CaptureRecord captureRecord,
        string imageHtml,
        string projectName,
        string boardOrDevice,
        string technician,
        string sourceName,
        string notesText)
    {
        return $$"""
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Lab Imager Evidence Report</title>
<style>
body{background:#e5e7eb;font-family:Segoe UI,Arial,sans-serif;margin:0;padding:20px;color:#111827}
.page{width:8.5in;min-height:11in;background:white;margin:auto;padding:.55in;box-shadow:0 10px 30px rgba(0,0,0,.15)}
.header{border-bottom:4px solid #991b1b;padding-bottom:18px}
.top{display:flex;justify-content:space-between;gap:20px;align-items:center}
.logo{font-size:38px;width:80px;height:60px;display:flex;align-items:center;justify-content:center}
h1{margin:0;font-size:30px;letter-spacing:.04em}
.subtitle{font-size:15px;color:#4b5563;text-align:right}
.banner{margin-top:15px;background:#0f172a;color:white;padding:10px 16px;font-weight:700}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:20px}
.card{border:1px solid #d1d5db;background:#f8fafc;padding:10px}
.label{font-size:11px;color:#666;text-transform:uppercase;letter-spacing:.04em}
.value{font-weight:700;margin-top:3px;word-break:break-word}
.section{margin-top:20px}
.section h3{margin:0 0 8px 0;border-bottom:1px solid #d1d5db;padding-bottom:6px}
.notes{border:1px solid #d1d5db;background:#fff;padding:15px;min-height:70px;white-space:pre-wrap;line-height:1.45}
.imgbox{border:1px solid #d1d5db;padding:10px;background:#fff}
.evidence-image{display:block;max-width:100%;height:auto;margin:auto}
.footer{margin-top:25px;border-top:1px solid #ccc;padding-top:10px;color:#666;font-size:12px;display:flex;justify-content:space-between}
@media print{
    body{background:white;padding:0}
    .page{box-shadow:none;margin:0;width:auto;min-height:auto}
}
</style>
</head>
<body>
<div class="page">
<div class="header">
<div class="top">
<div class="logo">??</div>
<div>
<h1>LAB IMAGER</h1>
<div class="subtitle">Evidence Report</div>
</div>
</div>
<div class="banner">Capture ID: {{WebUtility.HtmlEncode(captureRecord.CaptureId)}}</div>
</div>

<div class="grid">
<div class="card"><div class="label">Project</div><div class="value">{{Encode(projectName)}}</div></div>
<div class="card"><div class="label">Board / Device</div><div class="value">{{Encode(boardOrDevice)}}</div></div>
<div class="card"><div class="label">Technician</div><div class="value">{{Encode(technician)}}</div></div>
<div class="card"><div class="label">Timestamp</div><div class="value">{{captureRecord.CapturedAt:yyyy-MM-dd HH:mm:ss}}</div></div>
<div class="card"><div class="label">Source</div><div class="value">{{Encode(sourceName)}}</div></div>
<div class="card"><div class="label">Application</div><div class="value">Lab Imager</div></div>
</div>

<div class="section">
<h3>Technician Notes</h3>
<div class="notes">{{Encode(string.IsNullOrWhiteSpace(notesText) ? "(none)" : notesText.Trim())}}</div>
</div>

<div class="section">
<h3>Evidence Image</h3>
<div class="imgbox">
{{imageHtml}}
</div>
</div>

<div class="footer">
<div>Generated by Lab Imager</div>
<div>Report Version 1.0</div>
</div>
</div>
</body>
</html>
""";
    }

    private static string BuildImageHtml(string imagePath)
    {
        if (string.IsNullOrWhiteSpace(imagePath) || !File.Exists(imagePath))
        {
            return "<div>Evidence image was not found.</div>";
        }

        var extension = Path.GetExtension(imagePath).ToLowerInvariant();
        var mimeType = extension switch
        {
            ".jpg" or ".jpeg" => "image/jpeg",
            ".png" => "image/png",
            _ => "application/octet-stream"
        };

        var bytes = File.ReadAllBytes(imagePath);
        var base64 = Convert.ToBase64String(bytes);

        return $"""<img class="evidence-image" src="data:{mimeType};base64,{base64}" alt="Evidence Image">""";
    }

    private static string Encode(string value)
    {
        return WebUtility.HtmlEncode(value ?? string.Empty);
    }
}
